# Generated by Django 5.0.4 on 2024-07-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiPecasGeral',
            fields=[
                ('cod_empresa', models.IntegerField(db_column='COD_EMPRESA', primary_key=True, serialize=False)),
                ('empresa', models.CharField(db_column='EMPRESA', max_length=100)),
                ('compras', models.DecimalField(db_column='COMPRAS', decimal_places=2, max_digits=10)),
                ('estoque', models.DecimalField(db_column='ESTOQUE', decimal_places=2, max_digits=10)),
                ('objetivo_pecas', models.DecimalField(db_column='OBJETIVO_PECAS', decimal_places=2, max_digits=10)),
                ('objetivo_pecas_diario', models.DecimalField(db_column='OBJETIVO_PECAS_DIARIO', decimal_places=2, max_digits=10)),
                ('total_pecas_geral', models.DecimalField(db_column='TOTAL_PECAS_GERAL', decimal_places=2, max_digits=10)),
                ('pecas_geral_mes_anterior', models.DecimalField(db_column='PECAS_GERAL_MES_ANTERIOR', decimal_places=2, max_digits=10)),
                ('margem_per', models.DecimalField(db_column='MARGEM_PER', decimal_places=2, max_digits=5)),
                ('total_pecas_oficina', models.DecimalField(db_column='TOTAL_PECAS_OFICINA', decimal_places=2, max_digits=10)),
                ('objetivo_oficina', models.DecimalField(db_column='OBJETIVO_OFICINA', decimal_places=2, max_digits=10)),
                ('objetivo_oficina_diario', models.DecimalField(db_column='OBJETIVO_OFICINA_DIARIO', decimal_places=2, max_digits=10)),
                ('total_servico', models.DecimalField(db_column='TOTAL_SERVICO', decimal_places=2, max_digits=10)),
                ('total_servico_mes_passado', models.DecimalField(db_column='TOTAL_SERVICO_MES_PASSADO', decimal_places=2, max_digits=10)),
                ('passagem', models.DecimalField(db_column='PASSAGEM', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'BI_PECAS_GERAL',
                'managed': False,
            },
        ),
    ]
