# Generated by Django 5.0.4 on 2024-07-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiOficinaDetalhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_empresa', models.IntegerField()),
                ('empresa', models.CharField(max_length=100)),
                ('pecas_oficina_abertas', models.IntegerField()),
                ('serv_oficina_aberto', models.IntegerField()),
                ('total_oficina_aberto', models.IntegerField()),
                ('total_os_fechado', models.IntegerField()),
                ('objetivo_pecas', models.IntegerField()),
                ('objetivo_pecas_diario', models.IntegerField()),
                ('objetivo_pecas_diario_atual', models.IntegerField()),
                ('pecas_oficina_fechado', models.IntegerField()),
                ('pecas_oficina_mes_anterior', models.IntegerField()),
                ('pecas_oficina_cliente', models.IntegerField()),
                ('pecas_oficina_garantia', models.IntegerField()),
                ('pecas_oficina_interno', models.IntegerField()),
                ('objetivo_servico', models.IntegerField()),
                ('objetivo_oficina_diario', models.IntegerField()),
                ('objetivo_serv_diario_atual', models.IntegerField()),
                ('serv_oficina_fechado', models.IntegerField()),
                ('serv_oficina_mes_anterior', models.IntegerField()),
                ('serv_cliente_fechada', models.IntegerField()),
                ('serv_garantia_fechado', models.IntegerField()),
                ('serv_interno_fechado', models.IntegerField()),
                ('serv_cliente_abertas', models.IntegerField()),
                ('serv_garantia_abertas', models.IntegerField()),
                ('serv_interno_abertas', models.IntegerField()),
                ('orcamento_abertos_servico', models.IntegerField()),
                ('orcamento_abertos_pecas', models.IntegerField()),
                ('orcamento_abertos_total', models.IntegerField()),
                ('orcamento_fechados_total', models.IntegerField()),
                ('passagem', models.IntegerField()),
                ('entregue_no_prazo', models.IntegerField()),
                ('entregue_fora_prazo', models.IntegerField()),
                ('qtde_oficina', models.IntegerField()),
                ('total_perdido_oficina', models.IntegerField()),
                ('ticket_medio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('relacao_pecas_mo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bi_oficina_detalhado',
                'managed': False,
            },
        ),
    ]
