# Generated by Django 5.0.4 on 2024-07-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbs', '0003_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina_Servico',
            fields=[
                ('NUMERO_OS', models.IntegerField(primary_key=True, serialize=False)),
                ('COD_EMPRESA', models.IntegerField()),
                ('COD_SERVICO', models.IntegerField()),
                ('DESCRICAO_SERVICO', models.CharField(db_column='DESCRICAO_SERVICO', max_length=100)),
                ('ITEM', models.CharField(max_length=100)),
                ('DATA_EMISSAO', models.DateField()),
                ('TEMPO_PADRAO', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'bi_api_oficina_servico',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='oficina',
            options={'managed': False},
        ),
    ]
