# Generated by Django 5.0.4 on 2024-08-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbs', '0005_alter_oficina_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina_Tempos',
            fields=[
                ('NUMERO_OS', models.IntegerField(primary_key=True, serialize=False)),
                ('COD_EMPRESA', models.IntegerField()),
                ('COD_SERVICO', models.IntegerField()),
                ('COD_TECNICO', models.IntegerField()),
                ('ITEM', models.CharField(max_length=100)),
                ('DATA_ENTRADA', models.DateField()),
                ('HORA_ENTRADA', models.TimeField()),
                ('TEMPO_PAGO', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DATA_SAIDA', models.DateField()),
                ('HORA_SAIDA', models.TimeField()),
            ],
            options={
                'db_table': 'OS_TEMPOS_EXECUTADOS',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='oficina',
            table='bi_api_oficina',
        ),
    ]
